#!/bin/bash

PASS=`openssl rand -hex 24`
SALT=`openssl rand -hex 24`

CREDENTIAL_FILE_NAME=$1

touch $CREDENTIAL_FILENAME
chmod 755 $CREDENTIAL_FILENAME

#TODO only echo these lines if $CREDENTIAL_FILENAME is empty

echo "export GIT_ENCRYPT_PASS_FIXED=$PASS" >> $CREDENTIAL_FILENAME
echo "export GIT_ENCRYPT_SALT_FIXED=$SALT" >> $CREDENTIAL_FILENAME
